#!/usr/bin/env node

/**
 * KWC Form Link Generation Script
 * Generates :::render:kdform render cards from environment config and page metadata
 * Zero external dependencies, uses only Node.js built-in modules
 * Common infrastructure functions from ./_shared.mjs
 *
 * Render cards must be generated by this script; hand-assembling JSON is prohibited.
 */

import { readFileSync } from 'node:fs'

import {
  createFatal,
  parseArgs,
  loadEnvConfig,
  normalizeUrl,
} from './_shared.mjs'

const fatal = createFatal('form-link')

// ─── Utility Functions ────────────────────────────────────────

/** Extract the value of a specified tag from a .page-meta.kwp file using regex */
function extractTag(content, tagName) {
  const match = content.match(new RegExp(`<${tagName}>([\\s\\S]*?)</${tagName}>`))
  return match ? match[1].trim() : null
}

// ─── Command Implementation ────────────────────────────────

function generate(opts) {
  // Validate required parameters
  if (!opts.pageMeta) {
    fatal('Missing required --pageMeta\nUsage: node form-link.mjs generate --pageMeta <path> [--formNumber <entity-formNumber>] [--env <envName>]')
  }

  // Read page metadata file
  let content
  try {
    content = readFileSync(opts.pageMeta, 'utf-8')
  } catch {
    fatal(`Failed to read page metadata file: ${opts.pageMeta}`)
  }

  // Extract pageName and title
  const pageName = extractTag(content, 'name')
  if (!pageName) {
    fatal('Could not extract <name> from page metadata. Please fill it in.')
  }

  const title = extractTag(content, 'masterLabel')
  if (!title) {
    fatal('Could not extract <masterLabel> from page metadata. Please fill it in.')
  }

  // Load environment config
  const env = loadEnvConfig(opts.env)

  // formNumber requires isv (the assembled metadata URL is queried by the backend with isv-based isolation)
  const formNumber = opts.formNumber
  if (formNumber && !env.isv) {
    fatal('Current env has no `isv` configured; cannot build entity metadata URL')
  }

  // Build output
  const baseUrl = normalizeUrl(env.url)
  const url = `${baseUrl}/?formId=${pageName}`

  const result = { title, url }

  // When the page is bound to a Cosmic backend entity, attach the entity field query API for frontend on-demand entity structure retrieval
  if (formNumber) {
    result.metadata = `${baseUrl}/kapi/v2/devportal/ai-meta/getEntityFields?formNumber=${formNumber}`
  }

  console.log(`:::render:kdform ${JSON.stringify(result)}:::`)
}

// ─── Main Flow ─────────────────────────────────────────────

function main() {
  const [command, ...rest] = process.argv.slice(2)

  if (command !== 'generate') {
    console.error('Usage: node form-link.mjs generate --pageMeta <path> [--formNumber <entity-formNumber>] [--env <envName>]')
    process.exit(1)
  }

  const opts = parseArgs(rest)
  generate(opts)
}

main()
